# Rename to .streamlit/secrets.toml for local runs (do NOT commit real secrets)
APP_ENV = "prod_week1"

SLACK_WEBHOOK = "https://hooks.slack.com/services/REDACTED"
JIRA_PROJECT = "DQ"
JIRA_ASSIGNEE_EMAIL = "owner@company.com"
